### ISSUE TITLE
Unexpected? Behavior when pressing return on a link.

### ISSUE THREAD

**Issue by phoenixanimations** [calvinwyoung/org-autolist#6]
Love the package, just noticed if I have a link in a list:
`+ Example: [[https://phys.org/news/2017-09-simple-chess-puzzle-key-1m.html][Neat chess problem.]]` 
and I have `(setq org-return-follows-link t)` on it actually will ignore the behavior of RET, and attempt to either use the newline, or org-meta-return.

I fixed it by modifying the if statement in **defadvice org-return**:
From:
`(if (org-at-item-p)`
to:
`(if (and (org-at-item-p) (not (and (eq 'org-link (get-text-property (point) 'face)) org-return-follows-link)))`

Now looking in org-mode they seem to have an additional check for urls:
`(let ((tprop (get-text-property (point) 'face)))
    (or (eq tprop 'org-link)
      (and (listp tprop) (memq 'org-link tprop)))))`
I'm unsure why org has to confirm it's a list as well. But I just thought l would let you know just in case you might want to add support for urls. Anyway thank you for this package it makes org-mode a lot more pleasant when writing todos/checklists.

**Comment by calvinwyoung** [comment]
@phoenixanimations Thanks for point this out (and sorry for the very delayed response -- been very busy with work these last few weeks). I just added a pull request to fix this issue, and will publish a release shortly.

**Comment by phoenixanimations** [comment]
@calvinwyoung Awesome, and no problem glad I could be of some help :).
