### ISSUE TITLE
make it also work with tables

### ISSUE THREAD

**Issue by amosbird** [calvinwyoung/org-autolist#7]
Hi, this is a convenient package. It would be great to support tables.

**Comment by calvinwyoung** [comment]
@amosbird Hey there, thanks for the feedback, and sorry for the delayed response. What did you have in mind for additional behavior while editing tables?

By default, org-mode already binds `<RET>` to `(org-table-next-row)`, which should insert a new row if necessary. The `<TAB>` key also moves between columns quite naturally. How else can we make editing tables more convenient?

**Comment by amosbird** [comment]
hi @calvinwyoung . I was thinking to make `RET` add new line when at the `eol` of current line. But I found that `<tab>` just works. Thanks for the help :)

**Comment by calvinwyoung** [comment]
No problem! Please let me know if you have any other ideas to make this package even more useful :)
